# NumPy Fundamentals

Welcome to **Day 9 of your Data Science Journey**! Today, we start learning about **NumPy (Numerical Python)**, which is the foundational library for scientific computing and data analysis in Python.

## What is NumPy?
NumPy is an open-source Python library that provides support for large, multi-dimensional arrays and matrices, along with a collection of high-level mathematical functions to operate on these arrays.

### Why do we need NumPy in Data Science?
You might wonder: *Why not just use standard Python lists?*
Standard Python lists are highly flexible because they can hold elements of different data types. However, this flexibility makes them slow and memory-intensive for large datasets. NumPy arrays resolve this limitation. Here is a comparison:

| Feature | Python Lists | NumPy Arrays (`ndarray`) |
| :--- | :--- | :--- |
| **Data Type** | Heterogeneous (can store integers, strings, floats together) | Homogeneous (all elements must be of the same type) |
| **Memory Layout** | Non-contiguous (elements are pointers scattered in memory) | Contiguous (stored next to each other in memory) |
| **Speed** | Slow (requires type checking and pointer dereferencing) | Extremely fast (processed close to CPU/hardware speed) |
| **Operations** | Elements must be modified in loops | Supports vectorized operations (no loops needed) |

### 🧠 Memory Structure Visualization:
```text
Python List (Pointers to Objects):
[ List Object ] ──► [Pointer 0] ──► [ Integer Object: 1 ]
                    [Pointer 1] ──► [ Integer Object: 2 ]
                    [Pointer 2] ──► [ Integer Object: 3 ]

NumPy Array (Contiguous Blocks of Raw Bytes):
[ Array Metadata ] ──► [ 1 ][ 2 ][ 3 ] (Raw binary memory values in contiguous blocks)
```

Let's import NumPy and test this performance difference!

In [1]:
!pip install numpy

   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ----- ---------------------------------- 1.6/12.3 MB 21.1 MB/s eta 0:00:01
   ---------------- ----------------------- 5.0/12.3 MB 17.8 MB/s eta 0:00:01
   ------------------------- -------------- 7.9/12.3 MB 15.2 MB/s eta 0:00:01
   ------------------------------- -------- 9.7/12.3 MB 14.7 MB/s eta 0:00:01
   ---------------------------------------- 12.3/12.3 MB 13.3 MB/s  0:00:01


In [ ]:
%pip install numpy

In [1]:
import numpy as np
import sys

print(f"NumPy Version: {np.__version__}")

NumPy Version: 2.4.6


---

## Module 1: Creating NumPy Arrays & Inspecting Attributes

The core data structure of NumPy is the **`ndarray`** (N-dimensional array). Let's explore the various ways to create arrays and check their characteristics.

### 1.1 Creating Arrays from Lists
You can convert standard Python lists or tuples into arrays using `np.array()`.

In [2]:
import numpy as np
list1=[10,20,40,50]
arr=np.array(list1)
print(arr*2)
print(type(arr))
print(list1)

[ 20  40  80 100]
<class 'numpy.ndarray'>
[10, 20, 40, 50]


In [2]:
list2=[[1,2,3],
       [4,5,6],
       [7,8,9]]
arr2d=np.array(list2)
print(list2)
print(arr2d)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Creating a 1D Array
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr_1d)
print("Type:", type(arr_1d))

# Creating a 2D Array (Matrix)
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

1D Array: [1 2 3 4 5]
Type: <class 'numpy.ndarray'>

2D Array:
 [[1 2 3]
 [4 5 6]]


### 1.2 Defining Array Data Types (`dtype`)
NumPy allows you to explicitly specify the data type of the elements during array creation using the `dtype` parameter. Common types include: `np.int32`, `np.int64`, `np.float32`, `np.float64`, and `np.bool_`.

In [ ]:
# Creating an array with float data type
float_arr = np.array([1, 2, 3], dtype=np.float64)
print(float_arr)
print(float_arr.dtype)

Float Array: [1. 2. 3.]
Data Type: float64


### 1.3 Built-in Functions for Array Creation
Creating empty, filled, or structured arrays is highly useful for numerical computation. NumPy provides standard helpers:
* `np.zeros(shape)`: Creates an array filled with 0s.
* `np.ones(shape)`: Creates an array filled with 1s.
* `np.arange(start, stop, step)`: Creates an array with values from start to stop (exclusive).
* `np.linspace(start, stop, num)`: Creates an array with `num` evenly-spaced values over a specified interval (inclusive).
* `np.eye(n)`: Creates an identity matrix of size $n \times n$.

In [3]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [4]:
even=np.arange(0, 100, 2)
print(even)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [6]:
np.linspace(1, 5, 10) 

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [5]:
zeros = np.zeros((2, 3))  # 2 rows, 3 columns
ones = np.ones((3, 2))
range_arr = np.arange(0, 10, 2)  # Step of 2
linspace_arr = np.linspace(1, 5, 5)  # 5 numbers from 0 to 1
identity = np.eye(3)

print("Zeros Array:\n", zeros)
print("\nOnes Array:\n", ones)
print("\nArange Array:", range_arr)
print("\nLinspace Array:", linspace_arr)
print("\nIdentity Matrix:\n", identity)

Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]]

Ones Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]

Arange Array: [0 2 4 6 8]

Linspace Array: [1. 2. 3. 4. 5.]

Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 1.4 Array Attributes
Every NumPy array has specific attributes that provide structural details:
* `.ndim`: Number of dimensions (axes).
* `.shape`: Dimensions of the array (represented as a tuple: (rows, columns)).
* `.size`: Total number of elements in the array.
* `.dtype`: Data type of elements.
* `.itemsize`: Size of one array element in bytes.

In [ ]:
my_matrix = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)
print("Matrix:\n", my_matrix)
print(my_matrix.ndim)
print(my_matrix.shape)
print(my_matrix.size)
print(my_matrix.dtype)
print(my_matrix.itemsize)

Matrix:
 [[1 2 3]
 [4 5 6]]
Dimensions (ndim): 2
Shape (shape):      (2, 3)
Total size (size):  6
Data Type (dtype):  int32
Item size (bytes):  4


---

## Module 2: Indexing in NumPy

Indexing allows you to select single values or complete subsets from an array.

### 2.1 1D Array Indexing
Works exactly like Python list indexing (using `0` for the first element, `-1` for the last element).

In [7]:
list1=[10,20,30,40]
list1[-1]

40

In [8]:
salaries = np.array([10000, 20000, 30000, 40000, 50000])
salaries=salaries-(0.10*salaries)
print(salaries)

[ 9000. 18000. 27000. 36000. 45000.]


In [15]:
arr = np.array([10, 20, 30, 40, 50])
arr[-2]=500
print(arr)
print("First element [0]:", arr[0])
print("Third element [2]:", arr[2])
print("Last element [-1]: ", arr[-1])

[ 10  20  30 500  50]
First element [0]: 10
Third element [2]: 30
Last element [-1]:  50


### 2.2 2D Array Indexing (Matrices)
In standard Python, a 2D list of lists is indexed using `list_name[row][col]`. 
In NumPy, you can do this more efficiently using a single set of square brackets: **`array[row, col]`**.

In [12]:
arr=np.zeros((4,4))
arr[0,0]=1
arr[0,3]=1
arr


array([[1., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
arr=np.zeros((4,4))
arr[0,0]=1
arr[0,3]=1
arr[3,0]=1
arr[3,3]=1
arr

array([[1., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 1.]])

In [33]:
arr=np.zeros((3,3))
arr[0,0]=1
arr[1,1]=1
arr[2,2]=1
arr[0,2]=1
arr[2,0]=1

print(arr)

[[1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 1.]]


In [16]:
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
matrix[:,0:2]


array([[10, 20],
       [40, 50],
       [70, 80]])

In [20]:
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("Matrix:\n", matrix)
print("\nElement at row 0, column 1 [0, 1]: ", matrix[0, 1])
print("Element at row 2, column 2 [2, 2]: ", matrix[2, 2])
print("First row completely [0, :]:      ", matrix[0, :])
print("Second column completely [:, 1]:   ", matrix[:, 1])

Matrix:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]

Element at row 0, column 1 [0, 1]:  20
Element at row 2, column 2 [2, 2]:  90
First row completely [0, :]:       [10 20 30]
Second column completely [:, 1]:    [20 50 80]


### 2.3 Boolean Indexing (Filtering / Masking) 🌟
Boolean masking is one of the most powerful indexing techniques in NumPy. It allows you to select elements that meet specific logical conditions.

1. **Create a condition (mask):** Evaluating an operation like `arr > 5` returns a boolean array of the same shape.
2. **Apply the mask:** Passing the boolean array inside square brackets `arr[mask]` returns only elements where the condition is `True`.

In [1]:
import numpy as np

In [19]:
data = np.array([5, 12, 8, 21, 3, 14, 7])
print(data>12)
hot_days=data[data>12]
hot_days

[False False False  True False  True False]


array([21, 14])

In [4]:
data = np.array([5, 12, 8, 21, 3, 14, 7])
print(data>10)
data[data>10]


[False  True False  True False  True False]


array([12, 21, 14])

In [ ]:
data = np.array([5, 12, 8, 21, 3, 14, 7])
print("Original Array:", data)

# 1. Create a boolean mask for values greater than 10
mask = data > 10
print("Boolean Mask:  ", mask)

# 2. Filter elements using the mask
filtered_data = data[mask]
print("Filtered Data: ", filtered_data)

# Shortcut (Common standard syntax):
print("Shortcut filtering (data > 10):", data[data > 10])

#### Modifying elements with Boolean masks:
You can modify values that meet specific criteria in one line, without any loops.

In [ ]:
scores = np.array([45, 65, 30, 85, 92, 40])
print("Original Scores:", scores)

# Set all scores below 50 to 50 (passing baseline)
scores[scores < 50] = 50
print("Modified Scores: ", scores)

---

## Module 3: Slicing in NumPy (Views vs. Copies)

Slicing pulls out a range of elements using the `[start:stop:step]` format.

### 3.1 1D Slicing

In [ ]:
arr = np.array([0, 11, 22, 33, 44, 55, 66, 77])

print("Slice index 1 to 5 arr[1:5]:   ", arr[1:5])
print("Slice from start to 4 arr[:4]:  ", arr[:4])
print("Slice from 4 to end arr[4:]:    ", arr[4:])
print("Slice with step of 2 arr[::2]:  ", arr[::2])
print("Reverse array arr[::-1]:         ", arr[::-1])

### 3.2 2D Slicing
To slice a 2D matrix, specify row slicing and column slicing separated by a comma: **`matrix[row_start:row_stop, col_start:col_stop]`**.

In [ ]:
matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print("Matrix:\n", matrix)

# Extract first 2 rows and columns index 1 and 2
sub_matrix = matrix[0:2, 1:3]
print("\nSub-matrix (rows 0-1, cols 1-2):\n", sub_matrix)

# Extract all rows, column index 2
col_2 = matrix[:, 2]
print("\nAll rows, column index 2:", col_2)

### 3.3 Crucial Concept: Views vs. Copies ⚠️
* In standard Python, slicing a list creates a **new list** (a memory copy).
* In NumPy, slicing an array creates a **view** of the original array. This means no data is copied. The slice points to the same memory location as the original array.
* Modifying values inside a view **will change** the original array!
* To create a safe, independent copy, use the **`.copy()`** method.

In [7]:
original = np.array([10, 20, 30, 40, 50])
print("Original Array:", original)

# Create a slice (view)
my_slice = original[1:4]
print("Slice:", my_slice)

# Modify the slice
my_slice[0] = 999
print("\nModified Slice:", my_slice)
print("Original Array (Affected by the slice change!):", original)

Original Array: [10 20 30 40 50]
Slice: [20 30 40]

Modified Slice: [999  30  40]
Original Array (Affected by the slice change!): [ 10 999  30  40  50]


#### Correct approach: Using `.copy()`

In [ ]:
original = np.array([10, 20, 30, 40, 50])
print("Original Array:", original)

# Create an explicit copy
safe_copy = original[1:4].copy()
print("Safe Copy:", safe_copy)

# Modify copy
safe_copy[0] = 999
print("\nModified Copy:", safe_copy)
print("Original Array (Unchanged!):", original)

---

## Module 4: Broadcasting

Broadcasting is a powerful feature in NumPy that allows arithmetic operations to be performed on arrays of different shapes.

### 4.1 What is Broadcasting?
If you want to perform math on two arrays, they usually need to have matching dimensions. However, NumPy can stretch the smaller array across the larger array so that they have compatible shapes.

#### Simple Example: Adding a Scalar
Adding a scalar (shape `()`) to a 1D array (shape `(3,)`) works by stretching the scalar across the array elements:
```text
[ 10, 20, 30 ]  +  5  ===►  [ 10, 20, 30 ]  +  [ 5, 5, 5 ]  ===►  [ 15, 25, 35 ]
```

In [ ]:
arr = np.array([10, 20, 30])
print("Array + 5:", arr + 5)

### 4.2 Rules of Broadcasting
To determine if two arrays can be broadcast together, NumPy checks compatibility beginning with the rightmost dimension and working left:
1. **Are the dimensions equal?** If yes, they are compatible.
2. **Is one of the dimensions 1?** If yes, that dimension is stretched to match the other array.

If neither condition is met, NumPy raises a `ValueError: operands could not be broadcast together`.

#### Adding a 1D array to a 2D matrix:
Matrix Shape: `(2, 3)` (2 rows, 3 columns)  
1D Array Shape: `(3,)` (1 row, 3 columns)  

Since the rightmost dimensions match (`3` and `3`), they are compatible. The 1D array is broadcast (stretched) over the 2 rows:
```text
Matrix (2x3):              Vector (1x3):             Vector Stretched (2x3):
[[  1,  2,  3 ],      +    [ 10, 20, 30 ]   ===►     [[ 10, 20, 30 ],
 [  4,  5,  6 ]]                                      [ 10, 20, 30 ]]

Result Matrix (2x3):
[[ 11, 22, 33 ],
 [ 14, 25, 36 ]]
```

In [ ]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
vector = np.array([10, 20, 30])

result = matrix + vector
print("Matrix Shape:", matrix.shape)
print("Vector Shape:", vector.shape)
print("\nResult:\n", result)

---

## Module 5: Vectorization

**Vectorization** is the practice of performing math operations on entire arrays instead of looping through individual elements in Python.

### 5.1 Element-wise Operations
Arithmetic operations between arrays are computed **element-wise** automatically.

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Addition a + b:      ", a + b)
print("Subtraction b - a:   ", b - a)
print("Multiplication a * b:", a * b)
print("Division b / a:      ", b / a)
print("Exponentiation a**2: ", a ** 2)

### 5.2 Performance: Loop vs. Vectorization
Let's write a loop to square 1,000,000 numbers vs doing it via NumPy vectorization.

In [ ]:
numbers = np.arange(1000000)

print("Loop implementation time:")
%timeit [x ** 2 for x in numbers]

print("\nVectorized implementation time:")
%timeit numbers ** 2

---

## Module 6: Hands-On Practice Exercises!

Test your NumPy fundamentals by solving the exercises below. Write your code in the empty cell and run it.

### Exercise 1: Temperature Converter
1. Create a 1D NumPy array named `celsius_temps` containing: `[0, 10, 20, 25, 30, 37, 40]`.
2. Perform a vectorized operation to convert these temperatures to Fahrenheit. Formula: $F = C \times 9/5 + 32$.
3. Print the resulting array.

In [ ]:
# Write your Exercise 1 solution here:


### Exercise 2: Boolean Filter & Salary Cap
1. Create an array of employee salaries: `[45000, 78000, 120000, 32000, 95000, 50000]`.
2. Print the list of salaries that are greater than or equal to `60000` using boolean indexing.
3. Set all salaries below `40000` to a minimum baseline of `40000`. Print the updated salaries array.

In [ ]:
# Write your Exercise 2 solution here:


### Exercise 3: Matrix Slicing
Given the matrix below:
1. Slice and extract the inner $2 \times 2$ block: 
   ```python
   [[11, 12],
    [16, 17]]
   ```
2. Slice and print the third row completely.
3. Slice and print the first two elements of the last column.

In [ ]:
# Given matrix:
matrix = np.array([
    [5,  6,  7,  8],
    [9,  10, 11, 12],
    [14, 15, 16, 17],
    [18, 19, 20, 21]
])

# Write your slicing solutions below:


### Exercise 4: View Modification Protection
1. Create a 1D array: `[1, 2, 3, 4, 5]`.
2. Create a safe copy of the slice containing the first 3 numbers.
3. Double the values inside the copy.
4. Verify that the original array is unchanged.

In [ ]:
# Write your Exercise 4 solution here:


--- 

## Solutions (Double click to reveal & check!)

### Exercise 1 Solution
```python
celsius_temps = np.array([0, 10, 20, 25, 30, 37, 40])
fahrenheit_temps = celsius_temps * (9/5) + 32
print(fahrenheit_temps)
```

### Exercise 2 Solution
```python
salaries = np.array([45000, 78000, 120000, 32000, 95000, 50000])
print(salaries[salaries >= 60000])
salaries[salaries < 40000] = 40000
print(salaries)
```

### Exercise 3 Solution
```python
# 1. Inner 2x2 block
print(matrix[1:3, 2:4])

# 2. Third row completely
print(matrix[2, :])

# 3. First two elements of the last column
print(matrix[0:2, -1])
```

### Exercise 4 Solution
```python
arr = np.array([1, 2, 3, 4, 5])
safe_slice = arr[0:3].copy()
safe_slice *= 2
print("Original:", arr)
print("Copy:    ", safe_slice)
```

In [10]:
arr1=np.arange(0, 21, 1)
print(arr1%2==0)
arr1[arr1%2==0]

[ True False  True False  True False  True False  True False  True False
  True False  True False  True False  True False  True]


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])