# Day 6: NumPy Essentials for AI & Machine Learning

Welcome to **Day 6 of the Industrial Training for AI & Machine Learning**! Today, we transition from pure Python to **NumPy** (Numerical Python), the most important library for handling numbers, matrices, and datasets in AI.

In AI and Machine Learning, your data is always represented as grids of numbers (like rows of data, pixel values in images, or word frequencies in texts). While Python lists can store these numbers, they are very slow. NumPy introduces a special array structure that runs up to 100x faster than standard Python lists.

---

## Learning Objectives
By the end of this session, you will understand:
1. **NumPy Arrays vs. Python Lists**: Why NumPy is faster (Memory Layout).
2. **Creating Arrays & Attributes**: Creating 1D and 2D arrays, and checking `.shape` and `.dtype`.
3. **Vectorization**: Performing math operations on full datasets without writing slow `for` loops.
4. **Slicing & Indexing**: Extracting features ($X$) and labels ($y$) from a dataset.
5. **Data Cleaning & Filtering**: Using Boolean masks and `np.where()` to handle outliers or invalid data.
6. **Statistical Summaries & Broadcasting**: Calculating mean/standard deviation and standardizing data.
7. **Reshaping & Flattening**: Changing array structures for model inputs.

## 1. Introduction: Why NumPy Arrays?

- **Python Lists**: Store pointers to values scattered across your computer's memory. This makes them flexible but slow for doing heavy calculations.
- **NumPy Arrays**: Store numbers directly side-by-side in a **contiguous block of memory** of a single data type. This allows your CPU to perform operations on the numbers instantly.

Let's import `numpy` (usually as `np`) and create our first arrays:

In [4]:
list1=[10,20,30,40]
arr1=np.array(list1)
print(type(arr1))

<class 'numpy.ndarray'>


In [2]:
import numpy as np

# 1. Creating a 1D Array (a simple vector)
arr_1d = np.array([10, 20, 30, 40])
print("1D Array:", arr_1d)
print("Shape (size along dimensions):", arr_1d.shape) # returns (4,)
print("Data Type:", arr_1d.dtype)
print("Number of Dimensions:", arr_1d.ndim)
 
# 2. Creating a 2D Array (a matrix / tabular dataset)
data_matrix = np.array([
    [1.5, 2.0, 3.4],
    [4.0, 5.1, 6.2]
])
print("\n2D Array:\n", data_matrix)
print("Shape (rows, columns):", data_matrix.shape) # returns (2, 3)

# 3. Quick Creators for Initializing Variables
zeros = np.zeros((3, 3))        # 3x3 matrix of zeros
ones = np.ones((2, 4))          # 2x4 matrix of ones
sequence = np.arange(0, 10, 2)  # numbers from 0 to 9 stepping by 2

print("\nZeros Matrix:\n", zeros)
print("ones matrix:")
print(ones)
print("\nSequence:", sequence)

1D Array: [10 20 30 40]
Shape (size along dimensions): (4,)
Data Type: int64
Number of Dimensions: 1

2D Array:
 [[1.5 2.  3.4]
 [4.  5.1 6.2]]
Shape (rows, columns): (2, 3)

Zeros Matrix:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
ones matrix:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Sequence: [0 2 4 6 8]


## 2. Vectorization: Math Without Loops

If you want to perform math on every item in a Python list, you must write a `for` loop. In NumPy, you can do math operations directly on the array. NumPy applies the operation to every element automatically. This is called **vectorization**.

In [6]:
prices = np.array([100, 200, 300, 400])

# Vectorized operation: apply 10% tax on all prices
taxed_prices = prices * 1.10
print("Original prices:", prices)
print("Taxed prices:   ", taxed_prices)

# Adding two arrays element-wise
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
print("\nSum of a and b:", a + b)

Original prices: [100 200 300 400]
Taxed prices:    [110. 220. 330. 440.]

Sum of a and b: [11 22 33]


### Speed Comparison: Python Loop vs. NumPy Vectorization
Let's see the speed difference by adding one million numbers together:

In [7]:
import time
import numpy as np
size = 10000000
list1 = list(range(size))
list2 = list(range(size))
arr1 = np.arange(size)
arr2 = np.arange(size)

# Time taken using normal Python loops
start = time.time()
result_list = [list1[i] + list2[i] for i in range(size)]
loop_time = time.time() - start

# Time taken using NumPy vectorized operations
start = time.time()
result_arr = arr1 + arr2
numpy_time = time.time() - start

print(f"Python Loop Time:  {loop_time:.6f} seconds")
print(f"NumPy Vector Time: {numpy_time:.6f} seconds")
print(f"🚀 NumPy is {loop_time / numpy_time:.1f}x faster!")

Python Loop Time:  2.222312 seconds
NumPy Vector Time: 0.045127 seconds
🚀 NumPy is 49.2x faster!


## 3. Indexing & Slicing

In Machine Learning, datasets are 2D grids (matrices):
- **Rows** represent individual data samples (e.g., houses, patients, customers).
- **Columns** represent characteristics or features (e.g., area, number of rooms, price).

We slice arrays using: `array[row_indices, column_indices]`. The colon `:` means "select all" along that direction.

In [2]:
import numpy as np

In [3]:
dataset = np.array([
    [25, 50, 710],
    [47, 85, 690],
    [31, 62, 780],
    [19, 22, 620]
])
dataset[0,0]=0
dataset[0,2]=0
dataset[3,0]=0
dataset[3,2]=0
dataset

array([[  0,  50,   0],
       [ 47,  85, 690],
       [ 31,  62, 780],
       [  0,  22,   0]])

In [4]:
temp=np.array([20,30,10,25,15,28,3])
cold_days=temp[temp<20]
hot_days=temp[temp>25]
print(cold_days)
print(hot_days)


[10 15  3]
[30 28]


In [4]:
# Mock dataset: 4 samples (rows), 3 columns (features)
# Columns: [Age, Yearly Income (in Rs.1000s), Credit Score]
dataset = np.array([
    [25, 50, 710],
    [47, 85, 690],
    [31, 62, 780],
    [19, 22, 620]
])

# 1. Get a single value (Row 1, Column 1 -> Income of second person)
print("Income of second person:", dataset[1, 1])

# 2. Get an entire row (Third person's full details)
print("\nThird person details:", dataset[2, :])

# 3. Get an entire column (All Credit Scores)
print("\nAll credit scores:", dataset[:, 2])

# 4. Splits: Separating Input Features (X) from Target Labels (y)
# Let's say columns 0 and 1 are features (Age, Income), and column 2 is the label (Credit Score).
X = dataset[:, 0:2] # All rows, first two columns (0 and 1)
y = dataset[:, 2]   # All rows, only the last column (index 2)

print("\nFeatures X:\n", X)
print("\nLabels y:", y)

Income of second person: 85

Third person details: [ 31  62 780]

All credit scores: [710 690 780 620]

Features X:
 [[25 50]
 [47 85]
 [31 62]
 [19 22]]

Labels y: [710 690 780 620]


## 4. Data Filtering & Cleaning (Boolean Masking & `np.where`)

Datasets often contain mistakes, missing values, or outliers (e.g., negative salaries or zero values where it's impossible). NumPy allows us to filter these out easily.

In [10]:
salaries = np.array([45000, -999, 52000, 61000, -999, 48000])
fixed=np.where(salaries<0,10000,salaries)
print(fixed)


age=np.array([10,-25,67,120,-35,200])
fixed=np.where(age<0,-age,age)
agefinal=np.where(fixed>100,100,fixed)
print(agefinal)

[45000 10000 52000 61000 10000 48000]
[ 10  25  67 100  35 100]


In [1]:
import numpy as np
salaries = np.array([45000, -999, 52000, 61000, -999, 48000])

# 1. Find invalid placeholder values (e.g., where salary is -999)
is_invalid = salaries == -999
print("Boolean mask for invalid values:", is_invalid)

# 2. Filter out invalid values (Keep only positive salaries)
salaries[salaries < 0]=20000
print("Cleaned salaries list:", salaries)

# 3. Replace invalid values using np.where(condition, value_if_true, value_if_false)
# Let's replace all negative values with 0, and keep positive salaries as they are
fixed_salaries = np.where(salaries < 0, 0, salaries)
print("Salaries after replacing negatives with 0:", fixed_salaries)

Boolean mask for invalid values: [False  True False False  True False]
Cleaned salaries list: [45000 20000 52000 61000 20000 48000]
Salaries after replacing negatives with 0: [45000 20000 52000 61000 20000 48000]


In [15]:
salaries=np.array([20000,40000,-20000,50000,-10000])
new=np.where(salaries<0,0,salaries)
print(new)

[20000 40000     0 50000     0]


## 5. Statistical Summaries & Standardization (Broadcasting)

NumPy offers functions to calculate dataset metrics. 
- `axis=0`: Perform calculation column-wise (vertical down).
- `axis=1`: Perform calculation row-wise (horizontal across).

In [2]:
import numpy as np

In [11]:
x=np.array([10,40,20,30,40])
print(np.mean(x))
print(np.median(x))


28.0
30.0


In [13]:
X = np.array([
    [10.0, 200.0],
    [30.0, 100.0],
    [20.0, 300.0]
])
col_means = np.mean(X, axis=0)
row_means = np.mean(X, axis=1)
# 1. Calculate column-wise means (Average of column 0 and column 1 separately)
print("Column-wise Means:", col_means) # Returns [mean_col0, mean_col1]
print("row wise mean :",row_means)


Column-wise Means: [ 20. 200.]
row wise mean : [105.  65. 160.]


## 6. Reshaping & Flattening

AI models sometimes require inputs of specific shapes (e.g. flattening image pixels from a 2D matrix into a 1D vector).

In [ ]:
flat_arr = np.arange(6)
print("Original 1D array:", flat_arr)
# Reshape to a 2D matrix of 2 rows and 3 columns
matrix_2d = flat_arr.reshape(2, 3)
print(matrix_2d)
print("\nReshaped to 2x3 Matrix:\n", matrix_2d)

# Flatten it back to 1D
flattened = matrix_2d.flatten()
print(flattened)
print("\nFlattened array back to 1D:", flattened)

Original 1D array: [0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]

Reshaped to 2x3 Matrix:
 [[0 1 2]
 [3 4 5]]

Flattened array back to 1D: [0 1 2 3 4 5]


## 7. Bonus: Matrix Multiplication (The Dot Product)

In neural networks, we multiply inputs by weight grids to make predictions. In NumPy, matrix multiplication is done using the `@` operator or the `np.dot()` function.

In [8]:
inputs = np.array([1.0, 2.0]) 
print(inputs*5)

[ 5. 10.]


In [14]:
inputs = np.array([1.0, 2.0]) 
weights = np.array([
    [0.2, 0.8, -0.5],
    [0.5, -0.1, 0.4]
])
print(np.dot(inputs, weights))
# Compute neural output: inputs dot weights
outputs = np.dot(inputs, weights) # or inputs @ weights
print("Neural Layer Outputs:", outputs)

[1.2 0.6 0.3]
Neural Layer Outputs: [1.2 0.6 0.3]


---

## 8. Coding Exercises

### Exercise 1: Celsius to Fahrenheit (Vectorization)
Given a list of core temperature readings in Celsius:
1. Convert `celsius_list` into a NumPy array.
2. Convert all temperatures to Fahrenheit in a single vectorized line (no `for` loops!).
   - Formula: $F = (C \times 9/5) + 32$.

In [10]:
celsius_list = [0, 10, 25, 36.6, 40]
Celsius=np.array(celsius_list)
Fahrenite=(Celsius*(9/5))+32
print(Celsius)
print(Fahrenite)

[ 0.  10.  25.  36.6 40. ]
[ 32.    50.    77.    97.88 104.  ]


In [3]:
celsius_list = [0, 10, 25, 36.6, 40]
celsius=np.array(celsius_list)
F=(celsius*(9/5))+32
print(F)
# Write your code here:


[ 32.    50.    77.    97.88 104.  ]


### Exercise 2: Features and Label Splits (Slicing)
Given the custom student score database matrix below:
1. Extract columns 0, 1, and 2 into variable `X` (input features represent attendance, internal score, hours studied).
2. Extract only the last column (index 3) into variable `y` (target label represents final marks).

In [ ]:
# Columns: [Attendance %, Internal Score, Hours Studied, Final Marks]
student_data = np.array([
    [90, 18, 25, 85],
    [75, 14, 15, 62],
    [95, 19, 30, 92],
    [60, 10,  8, 45]])

X=student_data[:,0:3]
print(X)
Y=student_data[:,3]
print(Y)
# Write your code here:


[[90 18 25]
 [75 14 15]
 [95 19 30]
 [60 10  8]]
[85 62 92 45]


### Exercise 3: Filter & Replace Outliers (Data Cleaning)
In a dataset of customer ages, some records have corrupted values like `-1` (missing) or `999` (typo outlier).
1. Filter and print a clean array containing only valid customer ages (ages must be between `0` and `120` years).
2. Use `np.where()` to replace invalid values (any value less than 0 or greater than 120) with a default age of `30`. Print the updated array.

In [ ]:
age = np.array([25, -1, 47, 999, 18, 31, -5, 62])
new=np.where((age<0) | (age>120) , 30 , age)
print(new)
# Write your code here:


[25 30 47 30 18 31 30 62]


### Exercise 4: Normalize Features (Broadcasting)
Standardize input values for training a model using mean and standard deviation.
1. Calculate the column-wise mean of features matrix `X` below.
2. Calculate the column-wise standard deviation of `X` using `np.std()`.
3. Standardize `X` in a single line using broadcasting.
   - Formula: $X_{normalized} = \frac{X - mean}{std}$

In [ ]:
X = np.array([
    [10.0, 100.0],
    [20.0, 150.0],
    [30.0, 200.0]
])
mean=np.mean(X,axis=0)
std=np.std(X,axis=0)
normal = (X-mean)/std
print(normal)

# Write your code here:


[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]


---

## 9. Solutions to Coding Exercises

### Solution 1: Celsius to Fahrenheit (Vectorization)

In [ ]:
c_array = np.array(celsius_list)
f_array = (c_array * 9/5) + 32
print("Fahrenheit values:", f_array)

### Solution 2: Features and Label Splits (Slicing)

In [ ]:
# All rows, columns from start up to (excluding) index 3
X = student_data[:, 0:3]

# All rows, only column index 3 (last column)
y = student_data[:, 3]

print("Features X:\n", X)
print("\nLabels y:", y)

### Solution 3: Filter & Replace Outliers (Data Cleaning)

In [ ]:
# 1. Filter valid ages
valid_ages = customer_ages[(customer_ages >= 0) & (customer_ages <= 120)]
print("Valid customer ages:", valid_ages)

# 2. Replace outliers
corrected_ages = np.where((customer_ages < 0) | (customer_ages > 120), 30, customer_ages)
print("Corrected customer ages:", corrected_ages)

### Solution 4: Normalize Features (Broadcasting)

In [ ]:
means = np.mean(X, axis=0)
stds = np.std(X, axis=0)

# Broadcasted normalization
X_normalized = (X - means) / stds

print("Means: ", means)
print("Stds:  ", stds)
print("Normalized X:\n", X_normalized)

---
**Great Job!** You have completed the essential NumPy operations for data preprocessing. You are now fully prepared to handle dataset slicing, cleaning outliers, and feature scaling in AI pipelines!

Be sure to run `python day6_visualizer.py` in your terminal to see memory layouts, vectorization, slicing, and broadcasting rendered live in interactive 3D WebGL!